[2025-05-05 11:45:10,431] 97 werkzeug - WARNING -  * Debugger is active!
[2025-05-05 11:45:10,437] 97 werkzeug - INFO -  * Debugger PIN: 143-783-530
[2025-05-05 11:45:42,628] 34 root - INFO - Received form data:
[2025-05-05 11:45:42,633] 37 root - INFO - Location: washington
[2025-05-05 11:45:42,633] 37 root - INFO - Temperature: 23
[2025-05-05 11:45:42,633] 37 root - INFO - Humidity: 24
[2025-05-05 11:45:42,633] 37 root - INFO - Wind_Speed: 60
[2025-05-05 11:45:42,633] 37 root - INFO - Precipitation: 25
[2025-05-05 11:45:42,633] 37 root - INFO - Cloud_Cover: partly cloudy
[2025-05-05 11:45:42,635] 62 root - INFO - Dataframe Gathered
[2025-05-05 11:45:42,635] 51 root - INFO - Input DataFrame created:
[2025-05-05 11:45:42,644] 52 root - INFO - 
     Location  Temperature  Humidity  Wind_Speed  Precipitation    Cloud_Cover
0  washington         23.0      24.0        60.0           25.0  partly cloudy
[2025-05-05 11:45:42,644] 55 root - INFO - Initializing PredictPipeline...
[2025-05-05 11:45:42,644] 57 root - INFO - Making prediction...
[2025-05-05 11:45:42,644] 53 root - INFO - Exception Occured in load_object function utils
[2025-05-05 11:45:42,644] 69 root - ERROR - Error during prediction:
[2025-05-05 11:45:42,644] 71 root - ERROR - Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\app.py] line number [58] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\pipelines\Prediction_pipeline.py] line number [18] error message [Error occured in python script name [C:\Users\Praveen\OneDrive\Desktop\weather_prediction\src\Weather_prediction\utils\utils.py] line number [50] error message [[Errno 2] No such file or directory: 'Artifacts\\preprocessor.pkl']]]
[2025-05-05 11:45:42,654] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:45:42] "POST /predict HTTP/1.1" 200 -
[2025-05-05 11:45:42,785] 97 werkzeug - INFO - 127.0.0.1 - - [05/May/2025 11:45:42] "[36mGET /static/style.css HTTP/1.1[0m" 304 -
